name: "Bug Feedback"
description: "反馈启动器漏洞或其他问题。"
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        如果您不是整合包作者，请先向整合包作者反应。您可以在启动器的社区页内找到社区。  
        如果您是整合包作者，请确保您使用最新测试版。您可以在 actions 中下载最新测试版。
  - type: textarea
    id: bug-report
    attributes:
      label: 描述遇到的问题...
      description: 请描述问题，例如如何引发此问题，以及可能的解决方案。
    validations:
      required: true
