name: "Feature Request"
description: "提出新功能或改善的建议。"
labels: feature request
body:
  - type: markdown
    attributes:
      value: |
        如果您不是整合包作者，请先向整合包作者反应。您可以在启动器的社区页内找到社区。  
        如果您是整合包作者，与安装整合包无关且从未在官方仓库提出并关闭的功能，请先在官方仓库提出。在此仓库提交时，请先搜索是否存在相同且已被关闭的提议（此仓库中，不包含官方版），如不存在再提交。
  - type: textarea
    id: feature-request
    attributes:
      label: 描述您的提议...
      description: 请描述希望新增的功能，以及可能的实现方案。
    validations:
      required: true
