name: Android CI

on:
  workflow_dispatch:
    inputs:
      pkgSuffix:
        description: "Package Suffix"
        required: true
        default: "modpack"

jobs:
  ReleaseBuild:
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false
    name: Build ${{matrix.arch}}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: 'gradle'

      - name: Build ${{matrix.arch}} apk
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease -Darch="${{matrix.arch}}" -DpkgSuffix="${{github.event.inputs.pkgSuffix}}"

      - name: Upload ${{matrix.arch}} apk
        uses: actions/upload-artifact@v4
        with:
          name: app-release-${{matrix.arch}}
          path: FCL/build/outputs/*
          retention-days: 7
