name: Android CI test

on:
  workflow_dispatch:
    inputs:
      pkgSuffix:
        description: "Package Suffix"
        required: true
        default: "modpack"

jobs:
  DebugBuild:
    strategy:
      fail-fast: false
    name: Build Debug
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Prepare to Build ALL
        run: |
          chmod +x gradlew
          ./gradlew -Darch=all :FCL:mergeDebugAssets --rerun-tasks --no-build-cache


      - name: Build ALL apk
        run: |
          ./gradlew assembledebug -Darch="all" -DpkgSuffix="${{github.event.inputs.pkgSuffix}}" --stacktrace

      - name: Upload ALL apk
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-all
          path: FCL/build/outputs/*
          retention-days: 7

      - name: Prepare to Build ARM64
        run: |
          rm -rfv ./FCL/build/outputs/*
          ./gradlew -Darch=arm64 :FCL:mergeDebugAssets --rerun-tasks --no-build-cache

      - name: Build ARM64 apk
        run: |
          ./gradlew assembledebug -Darch="arm64" -DpkgSuffix="${{github.event.inputs.pkgSuffix}}" --stacktrace

      - name: Upload ARM64 apk
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-arm64
          path: FCL/build/outputs/*
          retention-days: 7
